# Generated by Django 2.2.10 on 2020-11-27 16:28

from django.db import migrations, models
import monuments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('monument_id', models.AutoField(primary_key=True, serialize=False)),
                ('monument_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('basicinfo', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=monuments.models.update_filename)),
            ],
        ),
    ]
