# Generated by Django 2.2 on 2020-11-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201102_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='guide',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tourist',
            old_name='tourist',
            new_name='user',
        ),
    ]
