# Generated by Django 2.2.10 on 2020-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201105_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
