# Generated by Django 2.2.10 on 2020-11-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='guidename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tourist',
            name='touristname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
