# Generated by Django 2.2.10 on 2020-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201130_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
