# Generated by Django 3.1.2 on 2020-11-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20201130_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('1', 'Payment Pending'), ('2', 'Payment Done')], max_length=1)),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guide')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tourist')),
            ],
        ),
    ]
