# Generated by Django 3.1.2 on 2020-11-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='guide_id',
            new_name='guidename',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='username',
        ),
    ]
