# Generated by Django 2.2.10 on 2020-12-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201201_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookings',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
