# Generated by Django 2.2.10 on 2020-12-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201201_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.CharField(max_length=50),
        ),
    ]
